http:
  services:
    dashdot:
      loadBalancer:
        servers:
          url: http://dashdot:3001

  routers:
    dashdot:
      rule: 'Host(`dashdot.example.com`)'
      entryPoints:
        - websecure
      tls:
        certresolver: default
      service: dashdot
      middlewares:
        - vpn-whitelist@docker
        - sablier@file