http:
  middlewares:
    sablier-dashdot:
      plugin:
        sablier:
          sablierUrl: http://sablier:10000
          names: dashdot
          group: homelab
          sessionDuration: 1m
          ignoreUserAgent: curl
          dynamic:
            displayName: Dashdot
            showDetails: true
            theme: hacker-terminal
            refreshFrequency: 5s