services:

  sablier:
    image: acouvreur/sablier:latest
    container_name: sablier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - sablier-net
      - traefik-net
    command:
      - start
      - --provider.name=docker
      - --logging.level=trace
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.dashdot.plugin.sablier.names=dashdot"
      - "traefik.http.middlewares.dashdot.plugin.sablier.sablierUrl=http://sablier:10000"
      - "traefik.http.middlewares.dashdot.plugin.sablier.sessionDuration=1m"
      - "traefik.http.middlewares.dashdot.plugin.sablier.dynamic.theme=hacker-terminal"
      - "traefik.http.middlewares.dashdot.plugin.sablier.dynamic.displayName=Dashdot"
      - "traefik.http.middlewares.dashdot.plugin.sablier.dynamic.refreshFrequency=1s"
      - "traefik.http.middlewares.dashdot.plugin.sablier.dynamic.showDetails=true"
      - "traefik.docker.network=traefik-net"

networks:

  sablier-net:
    name: sablier-net

  traefik-net:
    name: traefik-net
    external: true